### PR TITLE
Add support for TIFF files

### PR DESCRIPTION
**Pull request by ariep**
Tested with .NEF files from my old Nikon D50.

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
nice! I'll review a bit more in-depth later, but can you add a new testcase? What I've been doing is taking a sample image and resizing it to 1x1 pixels and putting it in tests.

**Comment by emmanueltouzery** [comment]
might be a little problematic with NEF files though, not sure whether they can be resized or something like that :-(

**Comment by emmanueltouzery** [comment]
(the reason to resize is not to put too big files in the repo)

**Comment by ariep** [comment]
Hm yeah, I haven't yet found a program that can edit the graphical content of a NEF file and save it again as NEF, so I'm not sure I can help you with the test.

**Comment by emmanueltouzery** [comment]
Can you make a second commit adding a test with a nef from your camera? You can take a fully black picture leaving the cap on for instance. Then i can see whether i can find a smaller sample file or we keep that one. The test should fail without your change.
Worst-case d50 nefs are presumably as small ad we're going to get nowadays :-)
If you make two commits i can possibly cherry-pick the first but take another image for the test.

**Comment by emmanueltouzery** [comment]
thank you for the PR! I've now merged it, then added a test. Unfortunately I had to pull in the repo a NEF file for testing. I picked the smallest I could find, a 3.9Mb nikon d1 file from http://www.rawsamples.ch/index.php/en/nikon
I've also deployed a new version on hackage, 0.6.1.0, with the new feature. Thank you again!

**Comment by ariep** [comment]
Great, thanks for adding the test and merging! I'll use it right away.

**Pull request merged**
