### PR TITLE
Raw support

### PR DESCRIPTION
**Pull request by bokesan**
Add Olympus ORF and Panasonic RW2 RAW file support.

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
maybe we should rename `findAndParseExifBlockNEF` to `findAndParseExifBlockRAW` or something more generic than NEF? Sorry I'm slow these days, busy on other tasks, I'll try to review also your other PR this week-end.

**Comment by bokesan** [comment]
I think `findAndParseExifBlockTiff` would be best - it's not (yet) raw-specific in any way.
And no hurry - I don't depend on having this on hackage. I'm just experimenting with hsexif right now. I'd love to have pure Haskell EXIF parsing, but hsexif is still a long way from exiv2 or exiftool. Actually what would be most useful to me at this time (meaning the next few months - again, no hurry) would be a sort of roadmap where you want to go with hsexif - just the simple and portable cases, or the full stuff including manufacturer-specific idiosyncrasies? Write-support? Non-mainstream file formats?

**Comment by emmanueltouzery** [comment]
Tiff sounds like a good name, you're right!

for hsexif, the issue is that it's basically in maintenance mode. I had plans to add write support, but the truth is that the library as it is suits my needs now, so for a while I've only been maintaining it, not adding features. I do agree that the other tools you mention are clearly ahead. Note that there are also haskell bindings to the C libexif library.

If you have serious plans to work on hsexif, I can give you write support on the repo. At the beginning you would do PRs on this repo, I would review and you can merge yourself, and then we can work from there.

**Comment by bokesan** [comment]
Thanks - that's what I wanted to know. I have one project where I can use HsExif as is, and another where I need more features than even libexif has. And I'd rather write applications than EXIF libraries, so I'll just continue forking an exiftool process.

**Comment by emmanueltouzery** [comment]
OK, taking another look at this one. The tests do pass, but are you sure it's OK to remove the case for `(0x4949,42)` which @ariep added a while back? You added new cases, but did you remove that one on purpose?

This time it's the last thing with this PR, I swear (I'd love to have a link for the magic numbers though, but if it's grabbed from many locations, not an authoritative one, not much we can do).

**Comment by bokesan** [comment]
I did remove it on purpose: It could never have worked because the `alignControl` test later in `parseTiffHeader` would have failed.

**Comment by emmanueltouzery** [comment]
great, thanks 👍 
I'll probably do a hsexif release tonight.

**Comment by bokesan** [comment]
I'm afraid there is no authoritative location for the formats. Many of them had to be reverse-engineered since the manufacturers did not release official docs. For HsExif, I think it's most important that it handles JPEG well, and if it supports a few raw formats too, so much the better. In particular if its the most common ones (Canon, Nikon, Sony). I'd rate features such as thumbnail extraction or makernotes support as more important than exhaustive raw format support. Adding file formats on an "as needed" basis seems ok to me.

**Comment by emmanueltouzery** [comment]
good points! 👍

**Comment by emmanueltouzery** [comment]
FYI I released 0.6.1.4 to hackage. Thank you again!

**Pull request merged**
