### PR TITLE
Fix reading of EXIF Sub-IDF located below IDF0

### PR DESCRIPTION
**Pull request by rudchenkos**
As it was already proposed in the comments in code, I have replaced the
offset arithmetics with lookAhead operations starting at the TIFF header
start. Inside of the tiff parsing procedure all IDFs and "external" tag
values are parsed in a separate pass, preserving the lookAhead origin.

The changes were triggred by a failure on a photo with IDF0 at non-usual
offset of 14938 and EXIF Sub-IDF residing as low as 244. I do not know
where that unusual data layout comes from, the photo was taken with
"Canon EOS 5D Mark III" and then processed by "Adobe Photoshop Lightroom
6.10 (Macintosh)".  The original sample photo cannot be provided for
legal reasons so I have fabricated the `test-exif-below-idf0.jpg` sample
from `test.jpg` using a hex editor

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
Amazing for fabricating a sample reproducing the issue!

I'll review ASAP, thank you.

**Comment by emmanueltouzery** [comment]
I started to review the patch. One thing is that I'm not fully comfortable with `lookAhead`, I'm not sure how much it's a good practice or not. But since the library already uses it and there are no issues, I guess it's moot.

So, regarding the patch, one thing I did in a branch => https://github.com/emmanueltouzery/hsexif/tree/just_test

single commit:
https://github.com/emmanueltouzery/hsexif/commit/5e292da59912d328d19ac964825bdfc4d3f5a77d

is to apply only the new test from your PR without the changes. And the test already passes with the old code. Can you modify the test so that it fails on the old code, succeeds with the new code? First I'm trying to understand exactly what issue we're fixing.

**Comment by rudchenkos** [comment]
Oh, snap. I have indeed started the development with a failing test, it just was the original file which I mention in the PR description. The fabricated sample does not reproduce the problem for me too.

I probably need to make a file which has referenced data (IDF1 or UserComment) _below_ IDF0, which has an unusually high offset in the reproducing file.

I have tried to strip all the sensitive data from the original file. Reducing the image to 1x1 grey pixel is easy to achieve with `jpegtran`. but I don't know a tool which can remove some EXIF tags **without moving IDF0**. While I can easily nullify simple tags like `Artist` using a hexeditor, the thumbnail is much harder do deal with.

I am really sorry for the confusion. I will get back to the PR with a proper sample failing on the `master` branch.

_on a side note: you named the test "parses LightRoom processed file" but I'm not sure LightRoom is the culprit. I have tried to process a photo with a Windows version of LightRoom and it produced IDF0 at the regular offset 8_

**Comment by rudchenkos** [comment]
Hi @emmanueltouzery 

I have prepared the minimal file reproducing the problem (using a hex editor again), which other EXIF tools parse correctly. It turns out that the the problem was indeed not in the unusual IDF0 offset itself, but in the fact that EXIF Sub-IDF was placed at lower offsets that IDF0. Such data layouts are not supported by the current implementation because it [irreversibly skips to IDF0](https://github.com/emmanueltouzery/hsexif/blob/master/Graphics/HsExif.hs#L283) during the TIFF header parsing. This is where `lookAhead` comes handy, allowing to "undo" the forward jumps.

The original failing file was rather conveniently failing the parser with "Cannot parse: not enough bytes" by sending it to parse data beyond the file size. The current example I have provided in the latest commit, just makes it parse some garbage instead of EXIF Sub-IDF. If I manage to fabricate a crashing example (which is still a valid JPEG), I will amend the test fixture once more.

**Comment by rudchenkos** [comment]
Ok, the latest test fixture I have pushed in this PR fails the test in `just_test` like this:
```
  tests/Tests.hs:71:
  1) parse IFD0 with offset > 8 parses LightRoom processed file
       Cannot parse: not enough bytes
```

**Comment by emmanueltouzery** [comment]
Ok, it's a bit hard for me to review the patch because there are a few independent cleanups mixed in with the actual fix. Ideally there would be 3-4 separate commits (like 'merge decodeEntry and decodeEntryWithHandler, introduce the IfEntry type, and so on).

But I follow the changes well enough to tell that each one of them is a progress compared to the current code, and I don't want to burden you as you've already made a great effort for this fix. And I feel that the tests protect us enough.

Thank you for a great contribution! I'll try to fix the iconv issue ASAP then I'll release a 0.7 version (must be a major version because we don't export exifIfdOffset and gpsTagOffset anymore).

**Comment by rudchenkos** [comment]
Thank you, Emmanuel! It is thrilling to give back to such great libraries. Thank you for making and sharing it!

I understand that the change set is non-trivial to review. Next time I can simply leave multiple commits in the review branch (each or them is an incomplete, but a logical step of the development) which you can squash before merging to master.

I honestly tried to make a minimal fix, but getting rid of the forward  skip pulled one change after another and here we are. It also took me several attempts to get it right. The core of it is, indeed, the new `IfEntry` allowing to _defer_ parsing of Sub-IDFs and external values back to the TIFF header level. On the bright side, the new structure should make it little easier to add parsing for new Sub-IDF types, like that IPCT.

**Comment by rudchenkos** [comment]
One of the things I have _not_ done to keep the changes at minimum: what do you thing about adding an alias for the `TagLocation` type? It is a great name in the context of tag definition, but it is somewhat confusing in the parser code:
```
parseIfd :: ByteAlign -> TagLocation -> Int -> Get [(ExifTag, ExifValue)]

data IfEntry = Tag ExifTag (Get ExifValue) | SubIFD TagLocation Int
```

What it really means here is "the type of IDF to  parse".  So having a simple alias would improve readability significantly:
```
data IDFId = ExifSubIFD | IFD0 | GpsSubIFD
alias TagLocation = IDFId

-- TAG DEFINITIONS REMAIN INTACT

parseIfd :: ByteAlign -> IDFId -> Int -> Get [(ExifTag, ExifValue)]

data IfEntry = Tag ExifTag (Get ExifValue) | SubIFD IDFId Int
```

**Comment by emmanueltouzery** [comment]
hmm I don't know, two names for the same thing sound like it could introduce some overhead/confusion. I'd think most people are not that familiar with exif details to really help many people. For possible contributors to hsexif/people who'll want to know the nitty-gritty, they can quickly see the definition of that type and understand what it is. We can change the apidoc for `TagLocation` to make it clear?

**Pull request merged**
